# Generated by Django 3.0.5 on 2020-05-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizator', '0002_auto_20200506_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizationsdata',
            name='file_date',
            field=models.CharField(default='May2020', max_length=20),
            preserve_default=False,
        ),
    ]
